In [39]:
from tensorflow.keras import layers

# 5 的意思是经过神经元后，维度转化为5维
# [b, 10] -> [b, 5]，b是句子数量
lstmcell = layers.LSTMCell(5)
rnncell = layers.SimpleRNNCell(5)
# 10 的意思是每个汉字的表示向量的维度是10
lstmcell.build(input_shape=(None,10))
rnncell.build(input_shape=(None,10))

for var in zip(lstmcell.trainable_variables,rnncell.trainable_variables):
    print(var[0].name,var[0].shape,var[0].dtype)
    print(var[1].name,var[1].shape,var[1].dtype)
    print('\n')

kernel:0 (10, 20) <dtype: 'float32'>
kernel:0 (10, 5) <dtype: 'float32'>


recurrent_kernel:0 (5, 20) <dtype: 'float32'>
recurrent_kernel:0 (5, 5) <dtype: 'float32'>


bias:0 (20,) <dtype: 'float32'>
bias:0 (5,) <dtype: 'float32'>




In [40]:
import tensorflow as tf

# 4个句子，且根据之前的设定，输出的维度是5维
# 4个句子并行进行前向计算
state0 = [tf.zeros([4, 5]),tf.zeros([4, 5])]
# 4个句子，每个句子7个字，每个字的表示向量维度是10维
x = tf.random.normal([4, 7, 10])
# 取每个句子的第一个字
xt = x[:,0,:]
# 前向计算
out, state1 = lstmcell(xt, state0)
print(out.shape, state1[0].shape,state1[1].shape)
print(id(out),id(state1[0]),id(state1[1]))

(4, 5) (4, 5) (4, 5)
140528429663152 140528429663152 140528531128160


In [41]:
state = state0
# 在序列长度维度上解开，循环送入 LSTM Cell 单元
for xt in tf.unstack(x, axis=1):
    # 前向计算
    out, state = lstmcell(xt, state)
    print(out.shape,state[0].shape,state[1].shape)


(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)
(4, 5) (4, 5) (4, 5)


In [43]:
import tensorflow as tf
from tensorflow.keras import layers

# 状态向量是5维
layer = layers.LSTM(5)
# 4句话，每句话7个字，每个字的表示向量是10维的
x = tf.random.normal([4, 7, 10])
out = layer(x)
print(out)
print('\n')

for var in layer.trainable_variables:
    print(var.name,var.shape,var.dtype)


tf.Tensor(
[[ 0.16966146  0.06215458  0.10828499 -0.17451651 -0.05830569]
 [-0.1442592  -0.02235897  0.14862593 -0.0923435   0.08713431]
 [ 0.04074397  0.1693563  -0.14727356  0.26403514 -0.22405092]
 [ 0.25786686  0.11899053  0.09351197  0.05225572 -0.09171846]], shape=(4, 5), dtype=float32)


lstm_1/lstm_cell_23/kernel:0 (10, 20) <dtype: 'float32'>
lstm_1/lstm_cell_23/recurrent_kernel:0 (5, 20) <dtype: 'float32'>
lstm_1/lstm_cell_23/bias:0 (20,) <dtype: 'float32'>
