In [1]:
import tensorflow as tf
from tensorflow.keras import layers

# 状态向量是5维
layer = layers.LSTM(5)
# 4句话，每句话7个字，每个字的表示向量是10维的
x = tf.random.normal([4, 7, 10])
out = layer(x)
print(out)
print('\n')

for var in layer.trainable_variables:
    print(var.name,var.shape,var.dtype)

tf.Tensor(
[[-0.07834458 -0.08115403 -0.0103028   0.01832303 -0.33299232]
 [ 0.05468381  0.02214921 -0.27454478 -0.06757024 -0.08186948]
 [-0.08695675  0.31371358 -0.05446488  0.16099833  0.2620947 ]
 [ 0.10625342 -0.30532357  0.01338917  0.01320605 -0.17113788]], shape=(4, 5), dtype=float32)


lstm/lstm_cell/kernel:0 (10, 20) <dtype: 'float32'>
lstm/lstm_cell/recurrent_kernel:0 (5, 20) <dtype: 'float32'>
lstm/lstm_cell/bias:0 (20,) <dtype: 'float32'>


In [2]:
import tensorflow as tf
from tensorflow.keras import layers,Sequential

net = Sequential([ # 构建 2 层 RNN 网络
# 除最末层外，都需要返回所有时间戳的输出，用作下一层的输入
layers.LSTM(5, return_sequences=True),
layers.LSTM(5),
])
# 4句话，每句话7个字，每个字的表示向量是10维的
x = tf.random.normal([4, 7, 10])
out = net(x)
print(out)
for var in net.trainable_variables:
    print(var.name,var.shape,var.dtype)

tf.Tensor(
[[ 0.01342524 -0.03180564  0.05031351  0.01574086  0.12032484]
 [-0.03389003  0.03127829  0.07479815  0.06893347  0.13489318]
 [-0.02699067  0.04662055  0.02154445  0.15134797 -0.03523358]
 [-0.09501531  0.12560178  0.1094329   0.14707239  0.08788656]], shape=(4, 5), dtype=float32)
lstm_1/lstm_cell_1/kernel:0 (10, 20) <dtype: 'float32'>
lstm_1/lstm_cell_1/recurrent_kernel:0 (5, 20) <dtype: 'float32'>
lstm_1/lstm_cell_1/bias:0 (20,) <dtype: 'float32'>
lstm_2/lstm_cell_2/kernel:0 (5, 20) <dtype: 'float32'>
lstm_2/lstm_cell_2/recurrent_kernel:0 (5, 20) <dtype: 'float32'>
lstm_2/lstm_cell_2/bias:0 (20,) <dtype: 'float32'>
